galaxy_info:
  author: PySlackers
  description: Python installer for any python version utilizing pythonz
  company: PySlackers
  license: MIT
  min_ansible_version: 2.1

  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
    - pyslackers
    - python
    - pythonz

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
