---
- name: Install fail2ban
  apt: pkg=fail2ban state={{ fail2ban_pkg_state }}
  when: ansible_os_family == 'Debian'
  tags: package

- name: Configure fail2ban local jails
  action: template src=jail.local.j2 dest=/etc/fail2ban/jail.local mode=0644
  notify: restart fail2ban
  tags: configuration

- name: Start/stop fail2ban service
  service: name=fail2ban state={{ fail2ban_service_state }} enabled={{ fail2ban_service_enabled }}
  tags: service