
python_apt_packages_2:
  - python
  - python-dev
  - python-pip

python_apt_packages_3:
  - python3
  - python3-pip
  - python3-dev

python_install_2: yes
python_install_3: yes

python_pip_packages: []
python_update_pip: no
python_update_setuptools: no
python_install_virtualenv: no
python_pip_executable: 
# python_pip_version:           # default to latest
# python_setuptools_version:    # default to latest
# python_virtualenv_version:    # default to latest
