---
- name: Clone AstroPlant into the configured directory.
  git:
    repo: "{{ astroplant_server_repo }}"
    dest: "{{ astroplant_server_dir }}"
    version: "{{ astroplant_server_version }}"
    update: "{{ astroplant_server_keep_updated }}"
    force: yes

- name: Set AstroPlant requirements path.
  set_fact:
    astroplant_server_requirements: "{{ astroplant_server_dir }}/requirements.txt"
    
- name: Install requirements.
  pip: 
    requirements: "{{ astroplant_server_requirements }}"
    virtualenv: /home/astroplant/astro_venv
    virtualenv_python: python3.4
    
- name: Copy uwsgi configuration.
  template:
    src: uwsgi.ini.j2
    dest: /home/astroplant/uwsgi.ini
    owner: astroplant
    mode: 0755
    
- name: Copy Nginx configuration.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: 0700
    notify: restart mysql
